name: Build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          # setup-rust-toolchain automatically uses Swatinem/rust-cache with some
          # default settings, but we need to tweak those settings to get a rust-cache
          # for each platform instead
          cache: false
          target: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: "${{ matrix.os }}-${{ matrix.target }}"

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/

  release:
    needs: build
    runs-on: ubuntu-latest

    # only run for pushes to `master` or creation of tags
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      # Download the artifacts from the build job
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R
      - name: Display available scopes
        run: 'curl -H "Authorization: Bearer $GH_TOKEN" https://api.github.com/user -Is | grep x-oauth-scopes'

      - name: Create release
        run: |
          gh release create ${{ github.ref_name }} ./artifacts/aarch64-apple-darwin/ ./artifacts/x86_64-apple-darwin/ ./artifacts/x86_64-unknown-linux-gnu/
